// JIR-97 regression guard. Dark Mode is a single `.dark` class on <html>
// (next-themes); every component's dark look comes from `dark:` Tailwind
// variants. If a `dark:` class references a color token Tailwind doesn't
// know (e.g. an undefined brand shade), Tailwind silently emits no CSS for
// it and that one element falls back to its Light Mode class while the rest
// of the page stays dark — a partial light/dark desync. This compiles the
// real globals.css with the project's Tailwind setup and asserts every
// brand-related `dark:` class used in the source actually produces a rule.
import { readFileSync, readdirSync, statSync } from "node:fs";
import path from "node:path";
import postcss from "postcss";
import tailwind from "@tailwindcss/postcss";
import { describe, expect, it } from "vitest";

const ROOT = path.resolve(__dirname, "../..");
const SRC = path.join(ROOT, "src");

function sourceFiles(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const full = path.join(dir, name);
    if (statSync(full).isDirectory()) return sourceFiles(full);
    return /\.tsx?$/.test(name) && !name.endsWith(".test.ts") ? [full] : [];
  });
}

const DARK_BRAND_CLASS = /(?<![\w:-])dark:(?:[a-z-]+:)*[a-z-]+-brand-[\w./[\]-]*[\w\]]/g;

function cssSelector(className: string): string {
  return "." + className.replace(/[:/.[\]]/g, (c) => `\\${c}`);
}

describe("Dark Mode brand classes", () => {
  it("every dark: brand class used in the source is generated by Tailwind", async () => {
    const used = new Set<string>();
    for (const file of sourceFiles(SRC)) {
      for (const match of readFileSync(file, "utf8").matchAll(DARK_BRAND_CLASS)) used.add(match[0]);
    }
    expect(used.size).toBeGreaterThan(0);

    const cssPath = path.join(SRC, "app/globals.css");
    const { css } = await postcss([tailwind({ base: ROOT })]).process(readFileSync(cssPath, "utf8"), { from: cssPath });

    const missing = [...used].filter((cls) => !css.includes(cssSelector(cls))).sort();
    expect(missing).toEqual([]);
  }, 60_000);
});
